"""
Generate a comprehensive inspection report summarizing all defects,
component mappings, and statistics.

Usage:
    python scripts/generate_report.py --output report/inspection_report.md
"""
import json
import sys
import argparse
from datetime import datetime
from pathlib import Path
from collections import Counter


def generate_markdown_report(
    defects: list[dict],
    components: list[dict],
    output_path: str,
):
    """Generate a markdown inspection report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    total = len(defects)
    
    # Aggregate stats
    by_class = Counter(d.get("defect_class", "unknown") for d in defects)
    by_severity = Counter(d.get("severity", "unknown") for d in defects)
    by_status = Counter(d.get("status", "unknown") for d in defects)
    by_floor = Counter(d.get("floor", "unknown") for d in defects)

    lines = [
        f"# AI Building Inspection Report",
        f"",
        f"**Generated:** {now}",
        f"",
        f"---",
        f"",
        f"## Summary",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total Defects | {total} |",
        f"| Total BIM Components | {len(components)} |",
        f"| Defects Mapped to Components | {sum(1 for d in defects if d.get('component_id'))} |",
        f"| Critical Defects | {by_severity.get('critical', 0)} |",
        f"| High Severity | {by_severity.get('high', 0)} |",
        f"| Medium Severity | {by_severity.get('medium', 0)} |",
        f"| Low Severity | {by_severity.get('low', 0)} |",
        f"",
        f"## Defects by Class",
        f"",
        f"| Class | Count | Percentage |",
        f"|-------|-------|------------|",
    ]

    for cls, count in sorted(by_class.items(), key=lambda x: -x[1]):
        pct = count / max(total, 1) * 100
        lines.append(f"| {cls} | {count} | {pct:.1f}% |")

    lines += [
        f"",
        f"## Defects by Floor",
        f"",
        f"| Floor | Count |",
        f"|-------|-------|",
    ]

    for floor, count in sorted(by_floor.items()):
        lines.append(f"| {floor} | {count} |")

    lines += [
        f"",
        f"## Status Distribution",
        f"",
        f"| Status | Count |",
        f"|--------|-------|",
    ]

    for status, count in sorted(by_status.items()):
        lines.append(f"| {status} | {count} |")

    # Critical/high defects detail
    critical_defects = [d for d in defects if d.get("severity") in ("critical", "high")]
    if critical_defects:
        lines += [
            f"",
            f"## Critical & High Severity Defects",
            f"",
            f"| ID | Class | Severity | Floor | Component | Notes |",
            f"|----|-------|----------|-------|-----------|-------|",
        ]
        for d in critical_defects[:50]:
            lines.append(
                f"| {d.get('id', '-')} "
                f"| {d.get('defect_class', '-')} "
                f"| {d.get('severity', '-')} "
                f"| {d.get('floor', '-')} "
                f"| {d.get('component_name', 'Not mapped')} "
                f"| {d.get('notes', '-') or '-'} |"
            )

    lines += [
        f"",
        f"---",
        f"",
        f"*Report generated by AI Building Inspection Platform*",
    ]

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"✓ Report saved to {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Generate inspection report")
    parser.add_argument("--defects", default="report/defects_export.json", help="Defects JSON file")
    parser.add_argument("--components", default=None, help="Components JSON file")
    parser.add_argument("--output", "-o", default="report/inspection_report.md", help="Output markdown file")
    args = parser.parse_args()

    # Load defects
    defects_path = Path(args.defects)
    if defects_path.exists():
        with open(defects_path, "r", encoding="utf-8") as f:
            defects = json.load(f)
    else:
        print(f"No defects file at {defects_path}. Using empty list.")
        defects = []

    # Load components
    components = []
    if args.components:
        comp_path = Path(args.components)
        if comp_path.exists():
            with open(comp_path, "r", encoding="utf-8") as f:
                components = json.load(f)
    else:
        # Try to find auto-generated components JSON
        for p in Path(".").glob("*_components.json"):
            with open(p, "r", encoding="utf-8") as f:
                components = json.load(f)
            break

    generate_markdown_report(defects, components, args.output)


if __name__ == "__main__":
    main()
